account/urls.py
from django.urls import path
from . views import UserRegisterView, UserEditProfileView, ChangePasswordView, ShowUserProfile, EditProfilePageView, CreateProfilePageVIew, ForgotPasswordView 
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),

    
   
    path('password/', ChangePasswordView.as_view(template_name='registration/change_password.html'), name='password'),
    path('changed_password_successfully/', views.changed_password_successfully, name='changed_password_successfully'),

    path('edit_profile/', UserEditProfileView.as_view(), name='edit_profile'),
    path('<int:pk>/profile', ShowUserProfile.as_view(), name='user_profile'),
    path('<int:pk>/edit_profile_page', EditProfilePageView.as_view(), name='edit_profile_page'),  
    path('create_profile_page/', CreateProfilePageVIew.as_view(), name='create_profile'),

    path('forgot_password/', ForgotPasswordView.as_view(), name='forgot_password'), 
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'), 
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

discussion/urls.py
from . import views
from django.urls import path
from . views import  DiscussionHomeView, DiscussionDetailsView, CreateDiscussionView, EditDiscussionPostView, DeleteDiscussionPostView
#from  django.views.generic.base import RedirectView




app_name = 'discussion'

urlpatterns = [
    path('discussion/', DiscussionHomeView.as_view(), name="discuss_list"),
    path('discussion/<int:pk>/', DiscussionDetailsView.as_view(), name='discuss_details'),
    path('create_discussion/', CreateDiscussionView.as_view(), name='create_discussion'),
    path('blog/edit/<int:pk>', EditDiscussionPostView.as_view(), name='edit_discussion_post' ),
    path('blog/<int:pk>/delete', DeleteDiscussionPostView.as_view(), name='delete_discussion_post' ),
    
    path('like/<int:pk>', views.DiscussionLikeView, name='like_post'),
     

    path('<int:pk>/add_comment/', views.add_discussion_comment, name='add_comment'),
]

index/urls.py
from . import views
from django.urls import path
from . views import  BlogHomeView, BlogDetailsView, AddPostView, EditPostView, DeletePostView, AddCategoryView, DraftsListView, AddDraftPostView, DraftPostDetailsView, EditDraftPostView, DeleteDraftPostView
from  django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage


app_name = 'index'

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),
    
    path('', views.home, name = 'home'),

    path('blog/', BlogHomeView.as_view(), name="blog_list"),
    path('blog/<int:pk>/', BlogDetailsView.as_view(), name='blog_details'),

    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('blog/edit/<int:pk>', EditPostView.as_view(), name='edit_post' ),
    path('blog/<int:pk>/delete', DeletePostView.as_view(), name='delete_post' ),
    path('like/<int:pk>', views.LikeView, name='like_post'),
    
    
    path('add_category/', AddCategoryView.as_view(), name='add_category'),       
    path('category/<str:category_name>/', views.CategoryView, name='category_list'), 
    path('view_category/', views.ListCategory, name='view_category'), 

    path('<int:pk>/add_comment/', views.add_comment, name='add_comment'),

    path('search/', views.search_results, name='search_results'),

    path('telecom/', views.telecom, name='telecom'),

    path('drafts/', DraftsListView.as_view(), name='drafts_list'),
    path('add_draft_post/', AddDraftPostView.as_view(), name='add_draft_post'),
    path('draft_details/<int:pk>/', DraftPostDetailsView.as_view(), name='draft_details'),
    path('draft/edit/<int:pk>', EditDraftPostView.as_view(), name='edit_draft_post' ),
    path('draft/<int:pk>/delete', DeleteDraftPostView.as_view(), name='delete_draft_post' ),
    path('publish/<int:draft_pk>/', views.publish_draft, name='publish_draft'),

]

job/urls.py
from django.shortcuts import render, redirect
from . import views
from django.urls import path
from . views import JobHomeView, JobDetailsView, AddJobPostView, EditJobPostView, DeleteJobPostView, AddJobCategoryView, JobDraftPostDetailsView, JobDraftsListView, AddJobDraftPostView, EditJobDraftPostView, DeleteJobDraftPostView
from  django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage



app_name = 'jobs'

urlpatterns = [
    path('job/', JobHomeView.as_view(), name="job_list"),
    path('job/<int:pk>/', JobDetailsView.as_view(), name='job_details'),


    path('add_job_post/', AddJobPostView.as_view(), name='add_job_post'),
    path('job/edit/<int:pk>', EditJobPostView.as_view(), name='edit_job_post' ),
    path('job/<int:pk>/delete', DeleteJobPostView.as_view(), name='delete_job_post' ),
    
    path('add_job_category/', AddJobCategoryView.as_view(), name='add_job_category'),       
    path('job_category/<str:category_name>/', views.JobCategoryView, name='job_category_list'), 
    path('view_job_category/', views.ListJobCategory, name='view_job_category'), 

    path('<int:pk>/add_job_comment/', views.add_job_comment, name='add_job_comment'),


    path('job_drafts/', JobDraftsListView.as_view(), name='job_drafts_list'),
    path('add_job_draft_post/', AddJobDraftPostView.as_view(), name='add_job_draft_post'),
    path('job_draft_details/<int:pk>/', JobDraftPostDetailsView.as_view(), name='job_draft_details'),
    path('job_draft/edit/<int:pk>', EditJobDraftPostView.as_view(), name='edit_job_draft_post' ),
    path('job_draft/<int:pk>/delete', DeleteJobDraftPostView.as_view(), name='delete_job_draft_post' ),
    path('publish/<int:job_draft_pk>/', views.publish_job_draft, name='publish_job_draft'),
]

learwithjdd/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls")),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')), 
    path('contact/', include('contact.urls')),
    path('job/', include('job.urls')),
    path('discussion/', include('discussion.urls')),
    path('tasks/', include('tasks.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

discussion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from ckeditor.fields import RichTextField
from mptt.models import MPTTModel, TreeForeignKey


# Create your models here.
class Discussion(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, unique=True)
    date = models.DateTimeField(auto_now_add=True)    
    content = RichTextField(blank=True, null=True, unique=True)   
    likes = models.ManyToManyField(User, related_name='discuss_posts')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('discussion:discuss_details', args=[str(self.id)] )

    def total_likes(self):
        return self.likes.count()
        





class Comment(MPTTModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='discuss_user')
    post = models.ForeignKey(Discussion, on_delete=models.CASCADE, related_name='discuss_comments')
    content = RichTextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)
    
    # MPTT implementation
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
 
    
    class MPTTMeta:
        order_insertion_by = ['-date']
    

    
    def __str__(self):
        return f"Comment By: {self.user}"

discussion/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from ckeditor.widgets import CKEditorWidget
from ckeditor.fields import RichTextField
from mptt.models import MPTTModel, TreeForeignKey
from mptt.forms import TreeNodeChoiceField
from . models import Comment



class DiscussionForm(forms.ModelForm):
    class Meta:
        model = models.Discussion
        fields = ('title', 'author',  'content')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id':'author', 'type': 'hidden'}),                    
            'content': forms.Textarea(attrs={'class': 'form-control'}),           
        }




class NewCommentForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) 
         
        self.fields['parent'].required = False 
        self.fields['parent'].label = ''
        self.fields['parent'].widget.attrs.update({'class': 'd-none'})

    class Meta:
        model = models.Comment
        fields = ('parent', 'content')

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

discussion/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from . import models
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
#from job.job_forms import NewCommentForm
from . forms import NewCommentForm
from . import forms
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
#from account.forms import NewCommentForm
from .models import Discussion, Comment
#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count



# create classes the views
class DiscussionHomeView(ListView):
    model = models.Discussion
    template_name = 'discussion/discuss_list.html'
    ordering = ['-date']



class DiscussionDetailsView(DetailView):
    model = models.Discussion
    template_name = 'discussion/discuss_details.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()

        # Get all comments for the post and order them by date (most recent first)
        comments = post.discuss_comments.filter(status=True).order_by('date')

        total_comments = comments.count()  # Get the total number of comments
        #context['comments'] = page_obj
        context['comments'] = comments
        context['comment_form'] = NewCommentForm()
        context['total_likes'] = post.total_likes()
        context['liked'] = post.likes.filter(id=self.request.user.id).exists()
        context['total_comments'] = total_comments  # Add total_comments to the context
        return context



def add_discussion_comment(request, pk):
    post = get_object_or_404(models.Discussion, pk=pk)
    comments = post.discuss_comments.filter(status=True)
    if request.method == "POST":
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.user = request.user
            user_comment.save()
            return redirect('discussion:discuss_details', pk=pk)
    else:
        comment_form = NewCommentForm()

    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'total_likes': post.total_likes(),
        'liked': post.likes.filter(id=request.user.id).exists(),
        'total_comments': comments.count(),
    }
    return render(request, 'discussion/discuss_details.html', context)





class CreateDiscussionView(CreateView):
    model = models.Discussion
    form_class = forms.DiscussionForm
    template_name = 'discussion/create_discussion_post.html'
    #fields = '__all__'



class EditDiscussionPostView(UpdateView):
    model = models.Discussion   
    template_name = 'discussion/edit_discussion_post.html'
    form_class = forms.DiscussionForm
    #success_url = 'discussion/discuss_details.html'



class DeleteDiscussionPostView(DeleteView):
    model = models.Discussion
    success_url = reverse_lazy('discussion:discuss_list')
    template_name = 'discussion/delete_discuss_post.html'
    
    

# Create the function views here.
def DiscussionLikeView(request, pk):
    post = get_object_or_404(models.Discussion, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        lked= False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('discussion:discuss_details', args=[str(pk)]))

discussion/templates/discussion/create_discussion_post.html
{% extends 'home/base.html' %} 
{% block title %}  Create a new discussion {% endblock %}

{% block body %} 
{% if user.is_authenticated %}
    <h1> CREATE A NEW DISCUSSION</h1>
       
    <br><br>
    <div class="form-group"> 
        <form method="POST">
            {% csrf_token %} 
            {{form.as_p}}
            {{form.media}}
            <button class="btn btn-primary"> Create Discussion </button>
        </form> <br><br>
    </div>
    <script>
        var author = "{{user.id}}";
        document.getElementById("author").value = author;

    </script>
{% else %} 
    
    <div class="alert alert-danger" role="alert">
        <p>You don't have the permission to access this page...</p>
        <p><a href="{% url 'login' %}">LOGIN</a> to create tasks</p>    
    </div>
{% endif %}


{% endblock %}

discussion/templates/discussion/delete_discuss_post.html
{% extends 'home/base.html' %} 
{% block title %}  Delete Discussion Post {% endblock %}

{% block body %} 
{% if user.is_authenticated %}
    <h1> DELETE DISCUSSED POST</h1><br> <br>
    <h3><em>Delete: </em>  {{object.title}} </h3>
    {% if object.author.id == user.id  %}
            <p>
                {{object.content | safe | truncatewords:"80"}}
            </p>

            <div class="form-group"> 
                <form method="POST">
                    {% csrf_token %}             
                    <button class="btn btn-danger">Delete</button>
                    <a href="{% url 'discussion:discuss_list' %}" class="btn btn-secondary">Cancel</a>
                </form> <br><br>
            </div>
    {% else %} 
            <h3>You don't have the access to delete this post</h3> <br> <br>
            <a class="btn btn-primary" href="{% url 'discussion:discuss_list' %}">View Previous Discussion/a> 
            <a class="btn btn-primary" href="{% url 'jobs:job_list' %}">View Job Posts</a>
            <a class="btn btn-primary" href="{% url 'index:blog_list' %}">View Blog Posts</a> <br><br><br> <br><br><br>
    {% endif %}

{% else %} 
    <h3>You don't have the permission to access this page....</h3> <br> <br>
    <a class="btn btn-primary" href="{% url 'index:home' %}">Go Home</a> <br><br><br>

{% endif %}
{% endblock %}

discussion/templates/discussion/discuss_details.html
{% extends 'home/base.html' %}
{% load static %}
{% load humanize %} <!---to display date in a natural time-->
{% load mptt_tags %}

{% block title %}{{ object.title }}{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="post-container">
                <div class="post-title">
                    <h1>{{ object.title | upper }}</h1>
                    {% if user.is_authenticated %}
                    <small>
                        <b>Last Updated:</b> {{ object.date }} | <b>Created By:</b> {{ object.author.first_name }}
                        {{ object.author.last_name }} |                         
                        {% if object.author.id == user.id %}
                        <a href="{% url 'discussion:edit_discussion_post' object.pk %}">(Edit)</a> |
                        <a href="{% url 'discussion:delete_discussion_post' object.pk %}">(Delete)</a>
                        {% endif %}
                    </small> <hr>
                    <p>
                        {{ object.content | safe }}
                    </p>
                    <hr> <br>

                    <form action="{% url 'discussion:like_post' object.pk %}" method="post">
                        {% csrf_token %}
                        {% if liked %}
                        <button type="submit" class="btn btn-danger" name="post_id" value="{{ object.id }}">Unliked
                        </button> - {{ total_likes }} Likes
                        {% else %}
                        <button type="submit" class="btn btn-success" name="post_id" value="{{ object.id }}">Likes -
                            {{ total_likes }}</button>
                        {% endif %}
                    </form>
                    {% else %}                    
                    <div >
                        <small>
                            <b>Last Updated:</b> {{ object.date }} | <b>Created By:</b> {{ object.author.first_name }}
                            {{ object.author.last_name }}
                        </small> <br> <br>
                        <p>
                            {{ object.content | safe }}
                        </p>
                        <hr>
                        <small>
                            <a href="{% url 'login' %}">Login</a> to Like Posts, Comment and create a topic -
                            {{ total_likes }} Likes
                        </small>
                    </div>
                    {% endif %}
                </div>
<br>
                     <!--- show the blogger info-->
                     <br>
  <div class="card mb-3" >                                                             
    <div class="card mb-3"  >
         <div class="row g-0">
            <div class="col-md-2">
                {% if object.author.profile.profile_pic %}
                    <img src="{{ object.author.profile.profile_pic.url }}" class="rounded-circle" alt="Author profile image" width="120" height="120">
                {% else %}
                    <img src="{% static 'images/profile_user_icon.png' %}" class="rounded-circle" alt="Default profile image" width="170" height="170">
                {% endif %}
            </div>
            
         <div class="col-md-10">
         <div class="card-body">
              <h5 class="card-title">{{object.author.first_name|safe}} {{object.author.last_name|safe}}</h5>

              <small  class="fw-lighter">
                   {% if object.author.profile.website_url %}
                   <a href="{{object.author.profile.website_url}}" target="_blank">Website </a>                                     
              {% endif %}


              {% if object.author.profile.facebook_url %}
                   |  <a href="{{object.author.profile.facebook_url}}" class="links" target="_blank">Facebook </a>                                  
              {% endif %}


              {% if object.author.profile.linkedln_url %}
                   |  <a href="{{object.author.profile.linkedln_url}}" class="links" target="_blank">Linkedln </a> 
              {% endif %}


              {% if object.author.profile.twitter_url %}
                   |  <a href="{{object.author.profile.twitter_url}}" class="links" target="_blank">Twitter </a> 
              {% endif %}

              {% if object.author.profile.instagram_url %}                                   
                   |  <a href="{{object.author.profile.instagram_url}}" class="links" target="_blank">Instagram </a>                                  
              {% endif %}                                   


              {% if object.author.profile.whatsapp_url %} 
                   |  <a href="{{object.author.profile.whatsapp_url}}" class="links" target="_blank"> WhatsApp </a>
              {% endif %}


              {% if object.author.profile.github_url %}

                   |  <a href="{{object.author.profile.github_url}}" class="links" target="_blank">GitHub </a> 
              {% endif %}

              </small>
              <p class="card-text">
                {% if object.author.profile and object.author.profile.id %}
                   {{object.author.profile.bio |truncatewords:"50" |safe}} 
                   ... <a href="{% url 'account:user_profile' object.author.profile.id %}" class="link-info link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                       Read More...
                   </a> 
                {% endif %}           
              </p>
              
             
          
          
         </div>
         </div>
         </div>
    </div>
  </div>

  <!---  End of show the blogger info-->


<br>


                <div>
                {% if user.is_authenticated %}
                    <div class="comment-form">                    
                        <h2>Make a new comment</h2>
                        <form id="myForm" method="POST" action="{% url 'discussion:add_comment' object.id %}">
                            {% csrf_token %}
                            {{ comment_form.as_p }}
                            {{ form.media }}
                            <button type="submit" class="btn btn-secondary">Add comment</button>
                        </form>
                {% endif %}
                    </div>

                    <br><br><br>
                    <h2>{{ total_comments }} Comment{{ total_comments|pluralize }}</h2> <hr>
                        <small>Discussion on: {{ object.title }}</small> <br>
                        <small>Scroll up if you can not find the reply box when clicked</small><hr>
                  
                    {% recursetree comments %} 
                            
                        <div id="{{node.id}}" class="parent-comment">  
                            <div class="d-flex">
                                <div class="p-2 flex-grow-1"><b>{{ node.user }}</b></div>
                                <div class="p-2"><small>{{ node.date }} ({{ node.date|naturaltime }})</small></div>
                            </div>                         
                            {{node.content|safe}}                                      
                            {% if node.level < 3 %}
                            {% if user.is_authenticated %}
                               <br> <button type="button" class="btn btn-primary" onclick="myFunction('{{ node.id }}')">Reply</button> 
                            {% endif %}
                            {% endif %}
                        </div>  
                            <br>
                            
                                {% if not node.is_leaf_node %} 
                                     <div  class="children-comment"> 
                                        {{ children }} 
                                    </div>

                                {% endif %}
                               
                    {% endrecursetree %}                
                    </div>
            
                    
                        <script>
                            function formExit() {
                                document.getElementById("newForm").remove();
                            }
                        
                            function myFunction(id) {
                                var existingForm = document.getElementById("newForm");
                                if (existingForm) {
                                    existingForm.remove();
                                }
                        
                                var reply = document.getElementById(id);
                                var formHTML = `
                                    <form id="newForm" method="POST" class="form-insert py-2" action="{% url 'discussion:add_comment' object.pk %}">
                                        <div class="d-flex">
                                            <div class="p-2 flex-grow-1"><h2>Reply</h2></div>
                                            <div class="p-2"><button type="button" class="btn btn-secondary btn-sm" onclick="formExit()">Close</button></div>
                                        </div>
                                        <select name="parent" class="d-none" id="id_parent">
                                            <option value="${id}" selected="${id}"></option>
                                        </select>
                                        <label for="id_content">Content:</label>
                                        <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea>
                                        {% csrf_token %}
                                        {{ form.media }} 
                                        {% if user.is_authenticated %}
                                        <button type="submit" class="btn btn-secondary btn-sm">Submit Reply</button>
                                        {% endif %}
                                    </form>
                                `;
                        
                                var container = document.createElement('div');
                                container.innerHTML = formHTML;
                                container.classList.add('my-2', 'p-2', 'border', 'border-gray');
                        
                                reply.parentNode.insertBefore(container, reply);
                            }
                        </script>
                               <br><br><a href="{% url 'discussion:discuss_list' %}" class="btn btn-primary">Back Discussed List</a><br><br>                          
                       
                
                    <br><br>                    
                </div>

                <br><br>
                
            </div>
        </div>
    </div>
</div>

<style>
    .post-title {
        margin: auto;
        text-align: justify;
        max-width: 55rem;
        width: 100%;
    }

    

    .parent-comment{
        border: 1px solid gray;
        padding: 1.3rem;
        text-align: justify;
        
    }
    .children-comment {
        margin-left: 2rem;        
        text-align: justify;
    }

    .comment-form {
        margin-bottom: 20px; /* Add some spacing at the bottom */
    }

    /* Style the CKEditor textarea */
    .ckeditor-textarea {
        width: 100%; /* Set the width to 100% to fill the container */
        height: 200px; /* Set an initial height for the textarea */
        resize: vertical; /* Allow vertical resizing */
        box-sizing: border-box; /* Include padding and border in the total height */
    }

    /* Adjust the textarea height for different screen sizes */
    @media (max-width: 767px) {
        /* For screens smaller than 768px (e.g., mobile devices) */
        .ckeditor-textarea {
            height: 150px; /* Adjust the height for mobile screens */
        }
    }
</style>


{% endblock %}

discussion/templates/discussion/discuss_list.html
{% extends 'home/base.html' %}
{% load humanize %}


{% block title %} Discussion Post {% endblock %} 


{% block body %} 

<div class="d-flex">
    <div class="p-2 w-100"><h1> CREATED TOPICS </h1></div>    
    <div class="p-2 flex-shrink-1" ><a href="{% url 'discussion:create_discussion' %}"><button> Create A New Topic </button></a></div>
</div>


    <br>
    
        <ol>
        {% for discuss in object_list %} 
        <li>
           <h4><a href="{% url 'discussion:discuss_details' discuss.pk %}"> {{discuss.title | upper}}</a></h4> 
           {% if user.is_authenticated %}
                <small>
                   <b>Date Created:</b>  {{discuss.date}}({{discuss.date | naturaltime}}) | <b>Created By: </b>                    
                        {{discuss.author.first_name}} {{discuss.author.last_name}} |                    
                {% if disucss.author.id == user.id  %}
                    | <a href="{% url 'discussion:edit_discussion_post' discuss.pk %}">(Edit)</a> 
                    | <a href="{% url 'discussion:delete_discussion_post' discuss.pk %}">(Delete)</a>
                {% endif %}    
                </small>    
                <p> 
                       <!---{{blog.content | truncatewords:"80" | safe}}--> 
                       {{discuss.content | safe | truncatewords:"30"}}
                </p>
        {% else %} 
                <small>
                   <b>  Date Created:</b>{{discuss.date}}({{discuss.date | naturaltime}})
                   | <b>Created By: </b>   {{discuss.author.first_name}} {{discuss.author.last_name}}                  
                </small>    
                <p>
                        <!-----{{blog.content | truncatewords:"80" | safe}}--->
                        {{discuss.content | safe | truncatewords:"30"}}
                </p>                
        {% endif %}
            
        </li> <br>
            
        
        {% empty %} 
            <h2>No recent discussion availabe at the moment....</h2>
        {% endfor %}
    </ol>


{% endblock %}

discussion/templates/discussion/edit_discussion_post.html
{% extends 'home/base.html' %} 
{% block title %}  Edit Discussion Post {% endblock %}

{% block body %} 
{% if user.is_authenticated %}
    <h1> UPDATE DISCUSSION POST</h1><br> <br>
    {% if object.author.id == user.id  %}
            <div class="form-group"> 
                <form method="POST">
                    {% csrf_token %} 
                    {{form.as_p}}
                    {{form.media}}
                    <button class="btn btn-primary"> Update </button>
                </form> <br><br>
            </div>
    {% else %} 
            <h3>You don't have the access to edit this post</h3> <br> <br>
            <a class="btn btn-primary" href="{% url 'discussion:discuss_list' %}">View Discussed Posts</a> 
            <a class="btn btn-primary" href="{% url 'index:blog_list' %}">View Blog Posts</a> 
            <a class="btn btn-primary" href="{% url 'index:job_list' %}">View Job Posts</a> <br><br><br>
    {% endif %}
{% else %} 
    <h3>You don't have the permission to access this page...</h3> <br><br>
    <a class="btn btn-primary" href="{% url 'index:home' %}">Go Home</a> <br><br><br>
{% endif %}
{% endblock %}