job/urls.py
from django.shortcuts import render, redirect
from . import views
from django.urls import path
from . views import JobHomeView, JobDetailsView, AddJobPostView, EditJobPostView, DeleteJobPostView, AddJobCategoryView, JobDraftPostDetailsView, JobDraftsListView, AddJobDraftPostView, EditJobDraftPostView, DeleteJobDraftPostView
from  django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage



app_name = 'jobs'

urlpatterns = [
    path('job/', JobHomeView.as_view(), name="job_list"),
    path('job/<int:pk>/', JobDetailsView.as_view(), name='job_details'),


    path('add_job_post/', AddJobPostView.as_view(), name='add_job_post'),
    path('job/edit/<int:pk>', EditJobPostView.as_view(), name='edit_job_post' ),
    path('job/<int:pk>/delete', DeleteJobPostView.as_view(), name='delete_job_post' ),
    
    path('add_job_category/', AddJobCategoryView.as_view(), name='add_job_category'),       
    path('job_category/<str:category_name>/', views.JobCategoryView, name='job_category_list'), 
    path('view_job_category/', views.ListJobCategory, name='view_job_category'), 

    path('<int:pk>/add_job_comment/', views.add_job_comment, name='add_job_comment'),


    path('job_drafts/', JobDraftsListView.as_view(), name='job_drafts_list'),
    path('add_job_draft_post/', AddJobDraftPostView.as_view(), name='add_job_draft_post'),
    path('job_draft_details/<int:pk>/', JobDraftPostDetailsView.as_view(), name='job_draft_details'),
    path('job_draft/edit/<int:pk>', EditJobDraftPostView.as_view(), name='edit_job_draft_post' ),
    path('job_draft/<int:pk>/delete', DeleteJobDraftPostView.as_view(), name='delete_job_draft_post' ),
    path('publish/<int:job_draft_pk>/', views.publish_job_draft, name='publish_job_draft'),
]

learwithjdd/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls")),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')), 
    path('contact/', include('contact.urls')),
    path('job/', include('job.urls')),
    path('discussion/', include('discussion.urls')),
    path('tasks/', include('tasks.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from . import views 
from . views import AddTaskView, TaskListView


app_name = 'tasks'
urlpatterns = [
    path('task_lists', TaskListView.as_view(), name='tasks_list'),
    path('add_tasks', AddTaskView.as_view() , name='add_tasks'),

    path("complete-task/", views.TaskCompleteView.as_view(), name="complete_task"),

    path("delete-completed-tasks/", views.DeleteCompletedTasksView.as_view(), name="delete_completed_tasks"),
    path("edit-task/<int:pk>/", views.EditTaskView.as_view(), name="edit_task"),
    path("delete-task/<int:pk>/", views.DeleteTaskView.as_view(), name="delete_task"),

    path('update_status/', views.UpdateStatusView.as_view(), name='update_status'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Tasks(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    name = models.CharField(max_length = 50, unique=True)
    description = models.CharField(max_length=100, unique=True)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()    
    completed = models.CharField(max_length=150)


    class Meta:
        verbose_name_plural = 'Task'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('tasks:tasks_list')

tasks/forms.py
from .models import Tasks
from django import forms




class TaskForm(forms.ModelForm):
    due_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    
    completed_choices = [
        ('Yes', 'Yes'),
        ('No', 'No'),
        ('In-Progress', 'In-Progress'),
        ('Yet to start', 'Yet to start')
    ]

    completed = forms.ChoiceField(choices=completed_choices, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Tasks
        fields = ('name', 'description', 'completed', 'start_date', 'due_date')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
#from . import models
from .models import Tasks
from .forms import TaskForm
from django.views.generic import  CreateView, ListView, DeleteView
from django.urls import reverse_lazy, reverse
from django.views import View
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin




# Create your views here.
class AddTaskView(CreateView):
    model = Tasks
    form_class = TaskForm
    template_name = 'tasks/add_tasks.html'
    success_url = reverse_lazy('tasks:tasks_list')

    def form_valid(self, form):
        form.instance.user = self.request.user 
        return super().form_valid(form)



    
class TaskListView(ListView):
    model = Tasks
    template_name = 'tasks/tasks_list.html'
    context_object_name = 'tasks'
    ordering = ['due_date']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            # Filter tasks based on the logged-in user
            queryset = queryset.filter(user=self.request.user)
        else:
            # If user is not authenticated, return an empty queryset
            queryset = Tasks.objects.none()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        completed_choices = [
            ('Yes', 'Yes'),
            ('No', 'No'),
            ('In-Progress', 'In-Progress'),
            ('Yet to start', 'Yet to start')
        ]
        context['completed_choices'] = completed_choices
        return context



class TaskCompleteView(LoginRequiredMixin, View):
    def post(self, request):
        task_id = request.POST.get("task_id")
        completed = request.POST.get("completed")

        try:
            task = Tasks.objects.get(id=task_id)
            task.completed = completed
            task.save()
            return JsonResponse({"success": True})
        except Tasks.DoesNotExist:
            return JsonResponse({"success": False, "error": "Task not found"})






class DeleteCompletedTasksView(View):
    def post(self, request):
        Tasks.objects.filter(status=True).delete()
        return redirect("tasks:tasks_list")



class EditTaskView(View):
    def get(self, request, pk):
        task = get_object_or_404(Tasks, pk=pk)
        form = TaskForm(instance=task)
        return render(request, "tasks/edit_tasks.html", {"form": form, "task": task})

    def post(self, request, pk):
        task = get_object_or_404(Tasks, pk=pk)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("tasks:tasks_list")
        return render(request, "tasks/edit_task.html", {"form": form, "task": task})



class DeleteTaskView(DeleteView):
    model = Tasks
    template_name = 'tasks/delete_task.html'
    success_url = reverse_lazy('tasks:tasks_list')




class UpdateStatusView(View):
    def post(self, request):
        task_id = request.POST.get("task_id")
        checked = request.POST.get("checked") == "true"

        try:
            task = Task.objects.get(id=task_id)
            task.status = checked
            task.save()
            return JsonResponse({"success": True})
        except Task.DoesNotExist:
            return JsonResponse({"success": False, "error": "Task not found"})

tasks/templates/tasks/add_tasks.html
{% extends 'home/base.html' %}

{% block title %} Add Task{% endblock %}

{% block body %}
  <h1>ADD A NEW TASK</h1>
  {% if user.is_authenticated %}
    <br><br>
    <div class="form-group"> 
      <form method="POST">
        {% csrf_token %} 
        {{ form.as_p }} 
        {{ form.media }}  
        <br><br>         
        <button class="btn btn-primary">Add Task</button>
      </form> <br><br>
    </div>

  {% else %} 

        <div class="alert alert-danger" role="alert">
            <p><a href="{% url 'login' %}">LOGIN</a> to create tasks</p>    
        </div>    
  {% endif %}

  
{% endblock %}

tasks/templates/tasks/delete_task.html
{% extends 'home/base.html' %}

{% block title %}Delete Task{% endblock %}

{% block body %}
  <h1>Delete Task</h1>

  {% if user.is_authenticated %}
        <p>Are you sure you want to delete the task "{{ object.name }}"?</p>

        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Delete</button>
            <a href="{% url 'tasks:tasks_list' %}" class="btn btn-secondary">Cancel</a>
        </form>
  {% else %} 
        <div class="alert alert-danger" role="alert">
            <p><a href="{% url 'login' %}">LOGIN</a> to Delete tasks</p>    
        </div>
    {% endif %}
{% endblock %}

tasks/templates/tasks/edit_tasks.html
{% extends 'home/base.html' %}

{% block title %} Edit Task {% endblock %}

{% block body %}
    <h1>Edit Task</h1>

    {% if user.is_authenticated %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary">Save</button>
            </form>
    {% else %} 
            <div class="alert alert-danger" role="alert">
                <p><a href="{% url 'login' %}">LOGIN</a> to Edit tasks</p>    
            </div>
    {% endif %}
{% endblock %}

tasks/templates/tasks/tasks_list.html
{% extends 'home/base.html' %}
{% load static %}
{% load humanize %}

{% block title %} MY TASKS {% endblock %}

{% block body %}
<div class="d-flex">
  <div class="p-2 w-100">
    <h1>MY TASKS</h1>
  </div>
  <div class="p-2 flex-shrink-1">
    <a href="{% url 'tasks:add_tasks' %}">
      <button>Create A New Task</button>
    </a>
  </div>
</div>
<br><br>

{% if user.is_authenticated %}
<table class="table table-success table-striped">
  <thead>
            <tr>
            <th>S/N</th>
            <th>Task Name</th>
            <th>Description</th>
            <th>Start Date</th>
            <th>Due Date</th>
            <th>Status</th>
            <th>Modify Tasks</th>
            </tr>
  </thead>

  <tbody>
        {% for task in tasks %}
        <tr>  
                <td>{{ forloop.counter }}</td>      
                <td>{{ task.name }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.start_date }} <em>({{ task.start_date|naturaltime }}) </em>  </td>
                <td>{{ task.due_date }} <em> ({{ task.due_date |naturaltime }}) </em> </td>
                <td>
                    <select id="status_{{ task.id }}" class="task-status-select">
                    {% for choice in completed_choices %}
                    <option value="{{ choice.0 }}" {% if choice.0 == task.completed %}selected{% endif %}>{{ choice.1 }}</option>
                    {% endfor %}
                    </select>
                </td>
                <td>
                    <a href="{% url 'tasks:edit_task' task.id %}">Edit</a>
                    <a href="{% url 'tasks:delete_task' task.id %}">Delete</a>
                </td>
        </tr>
        {% empty %}
                <tr>
                <td colspan="7">You have not added any tasks.</td>
                </tr>
        {% endfor %}
  </tbody>
</table>

<script>
            $(document).ready(function() {
            $(".task-status-select").change(function() {
                var taskId = $(this).attr("id").split("_")[1];
                var completed = $(this).val();
        
                $.ajax({
                type: "POST",
                url: "{% url 'tasks:complete_task' %}",
                data: {
                    task_id: taskId,
                    completed: completed,
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                },
                success: function(response) {
                    if (response.success) {
                    console.log("Status updated successfully");
                    } else {
                    console.log("Failed to update status");
                    }
                },
                error: function(xhr, textStatus, errorThrown) {
                    console.log("Error updating status: " + errorThrown);
                },
                });
            });
            });
  </script>
  
<script src="{% static 'js/jquery.min.js' %}"></script>

    {% else %}
            <br><br>
            <div class="alert alert-danger" role="alert">
            <p><a href="{% url 'login' %}">LOGIN</a> to view tasks</p>
            </div>
    {% endif %}

    <br> <br>
    <hr>
   <center>  <h3> My Daily/simple tasks </h3> </center>
{% endblock %}