account/urls.py
from django.urls import path
from . views import UserRegisterView, UserEditProfileView, ChangePasswordView, ShowUserProfile, EditProfilePageView, CreateProfilePageVIew, ForgotPasswordView 
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),

    
   
    path('password/', ChangePasswordView.as_view(template_name='registration/change_password.html'), name='password'),
    path('changed_password_successfully/', views.changed_password_successfully, name='changed_password_successfully'),

    path('edit_profile/', UserEditProfileView.as_view(), name='edit_profile'),
    path('<int:pk>/profile', ShowUserProfile.as_view(), name='user_profile'),
    path('<int:pk>/edit_profile_page', EditProfilePageView.as_view(), name='edit_profile_page'),  
    path('create_profile_page/', CreateProfilePageVIew.as_view(), name='create_profile'),

    path('forgot_password/', ForgotPasswordView.as_view(), name='forgot_password'), 
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'), 
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

index/urls.py
from . import views
from django.urls import path
from . views import  BlogHomeView, BlogDetailsView, AddPostView, EditPostView, DeletePostView, AddCategoryView, DraftsListView, AddDraftPostView, DraftPostDetailsView, EditDraftPostView, DeleteDraftPostView
from  django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage


app_name = 'index'

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),
    
    path('', views.home, name = 'home'),

    path('blog/', BlogHomeView.as_view(), name="blog_list"),
    path('blog/<int:pk>/', BlogDetailsView.as_view(), name='blog_details'),

    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('blog/edit/<int:pk>', EditPostView.as_view(), name='edit_post' ),
    path('blog/<int:pk>/delete', DeletePostView.as_view(), name='delete_post' ),
    path('like/<int:pk>', views.LikeView, name='like_post'),
    
    
    path('add_category/', AddCategoryView.as_view(), name='add_category'),       
    path('category/<str:category_name>/', views.CategoryView, name='category_list'), 
    path('view_category/', views.ListCategory, name='view_category'), 

    path('<int:pk>/add_comment/', views.add_comment, name='add_comment'),

    path('search/', views.search_results, name='search_results'),

    path('telecom/', views.telecom, name='telecom'),

    path('drafts/', DraftsListView.as_view(), name='drafts_list'),
    path('add_draft_post/', AddDraftPostView.as_view(), name='add_draft_post'),
    path('draft_details/<int:pk>/', DraftPostDetailsView.as_view(), name='draft_details'),
    path('draft/edit/<int:pk>', EditDraftPostView.as_view(), name='edit_draft_post' ),
    path('draft/<int:pk>/delete', DeleteDraftPostView.as_view(), name='delete_draft_post' ),
    path('publish/<int:draft_pk>/', views.publish_draft, name='publish_draft'),

]

job/urls.py
from django.shortcuts import render, redirect
from . import views
from django.urls import path
from . views import JobHomeView, JobDetailsView, AddJobPostView, EditJobPostView, DeleteJobPostView, AddJobCategoryView, JobDraftPostDetailsView, JobDraftsListView, AddJobDraftPostView, EditJobDraftPostView, DeleteJobDraftPostView
from  django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage



app_name = 'jobs'

urlpatterns = [
    path('job/', JobHomeView.as_view(), name="job_list"),
    path('job/<int:pk>/', JobDetailsView.as_view(), name='job_details'),


    path('add_job_post/', AddJobPostView.as_view(), name='add_job_post'),
    path('job/edit/<int:pk>', EditJobPostView.as_view(), name='edit_job_post' ),
    path('job/<int:pk>/delete', DeleteJobPostView.as_view(), name='delete_job_post' ),
    
    path('add_job_category/', AddJobCategoryView.as_view(), name='add_job_category'),       
    path('job_category/<str:category_name>/', views.JobCategoryView, name='job_category_list'), 
    path('view_job_category/', views.ListJobCategory, name='view_job_category'), 

    path('<int:pk>/add_job_comment/', views.add_job_comment, name='add_job_comment'),


    path('job_drafts/', JobDraftsListView.as_view(), name='job_drafts_list'),
    path('add_job_draft_post/', AddJobDraftPostView.as_view(), name='add_job_draft_post'),
    path('job_draft_details/<int:pk>/', JobDraftPostDetailsView.as_view(), name='job_draft_details'),
    path('job_draft/edit/<int:pk>', EditJobDraftPostView.as_view(), name='edit_job_draft_post' ),
    path('job_draft/<int:pk>/delete', DeleteJobDraftPostView.as_view(), name='delete_job_draft_post' ),
    path('publish/<int:job_draft_pk>/', views.publish_job_draft, name='publish_job_draft'),
]

learwithjdd/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls")),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')), 
    path('contact/', include('contact.urls')),
    path('job/', include('job.urls')),
    path('discussion/', include('discussion.urls')),
    path('tasks/', include('tasks.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from ckeditor.fields import RichTextField
from django.utils import timezone




# Create your models here.
class JobPost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    location = models.CharField(max_length=150)    
    category = models.CharField(max_length=150)    
    content = RichTextField(blank=True, null=True, unique=True)    

    def __str__(self):
        return f" {self.title}"

    def get_absolute_url(self):
        return reverse('jobs:job_details', args=[str(self.id)] )

    def delete_expired_posts(self):
        expired_posts = JobPost.objects.filter(deadline__lt=timezone.now())
        expired_posts.delete()
        


class JobCategory(models.Model):
    name = models.CharField(max_length= 150, unique=True)
    
    class Meta:
        verbose_name_plural = 'Job Category'


    def __str__(self):
        return self.name

    #def get_absolute_url(self):
     #   return reverse('jobs:job_details', args=[str(self.id)] )

    def get_absolute_url(self):
        return reverse('jobs:job_list' )


   
class JobSaveAsDraft(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=150)    
    category = models.CharField(max_length=150)    
    content = RichTextField(blank=True, null=True, unique=True) 
    

    def __str__(self):
        return f" {self.title}"

    def get_absolute_url(self):
        return reverse('jobs:job_draft_details', args=[str(self.id)] )




class JobComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(JobPost, on_delete=models.CASCADE, related_name='job_comments')
    content = RichTextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)
    
    
    class Meta:
        ordering = ('-date', )
    
    def __str__(self):
        return f"Comment By: {self.user}"

job/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . import models
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from . import job_forms
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from . job_forms import NewCommentForm
from .models import JobPost, JobComment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin





# create classes the views
class JobHomeView(ListView):
    model = models.JobPost
    template_name = 'jobs/job_list.html'
    ordering = ['-date']



class JobDetailsView(DetailView): 
    model = models.JobPost
    template_name = 'jobs/job_details.html'
    context_object_name = 'post'
    paginate_by = 5  # Number of comments per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()

        # Get all comments for the post and order them by date (most recent first)
        comments = post.job_comments.filter(status=True).order_by('-date')
        total_comments = comments.count()  # Get the total number of comments

        # Apply pagination to comments
        paginator = Paginator(comments, self.paginate_by)
        page_number = self.request.GET.get('page')

        try:
            page_obj = paginator.page(page_number)
        except PageNotAnInteger:
            # If page_number is not an integer, show the first page
            page_obj = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. page_number > number of pages), show the last page
            page_obj = paginator.page(paginator.num_pages)

        # Passing the data to the page context
        context['comments'] = page_obj
        context['comment_form'] = NewCommentForm()
        context['total_comments'] = total_comments  # Add total_comments to the context
        return context




def add_job_comment(request, pk):
    post = get_object_or_404(models.JobPost, pk=pk)
    comments = post.job_comments.filter(status=True)
    if request.method == "POST":
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.user = request.user
            user_comment.save()
            return redirect('jobs:job_details', post.pk)
    else:
        comment_form = NewCommentForm()
    return redirect('jobs:job_details', post.pk)






class AddJobPostView(CreateView):
    model = models.JobPost
    form_class = job_forms.CustomJobPostForm
    template_name = 'jobs/add_job_post.html'
    #fields = '__all__'


class AddJobCategoryView(CreateView):
    model = models.JobCategory
    template_name = 'jobs/add_job_category.html'
    fields = '__all__'



class EditJobPostView(UpdateView):
    model = models.JobPost    
    template_name = 'jobs/edit_job_post.html'
    form_class = job_forms.CustomJobPostForm
    

class DeleteJobPostView(DeleteView):
    model = models.JobPost
    success_url = reverse_lazy('jobs:job_list')
    template_name = 'jobs/delete_job_post.html'
    
    

# Create the function views here.

def JobCategoryView(request, category_name):
    try:      
        category = models.JobCategory.objects.get(name=category_name)       
        posts = models.JobPost.objects.filter(category=category)   
        return render(request, 'jobs/category_job_view.html', {
            'category': category,
            'posts': posts,            
        })
    except models.JobCategory.DoesNotExist:
        return render(request, 'home/category_not_found.html')
    except:
        return render(request, 'home/error.html')


def ListJobCategory(request):
    category_list = models.JobCategory.objects.all()    
    return render(request, 'jobs/job_category_list.html', {
            'category_list': category_list            
    })



# creating the code that save job post as a draft before publishing
class JobDraftsListView(LoginRequiredMixin, ListView):
    model = models.JobSaveAsDraft
    template_name = 'jobs/job_draft_list.html'
    ordering = ['-date']

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        return queryset.filter(author=user)



class AddJobDraftPostView(CreateView):
    model = models.JobSaveAsDraft
    form_class = job_forms.JobDraftPostForm
    template_name = 'jobs/save_job_as_draft.html'


    def form_valid(self, form): 
        form.instance.author = self.request.user
        return super().form_valid(form)


class JobDraftPostDetailsView(DetailView):
    model = models.JobSaveAsDraft
    template_name = 'jobs/drafts_job_details.html'    
   


def publish_job_draft(request, job_draft_pk):
    job_draft = get_object_or_404(models.JobSaveAsDraft, pk=job_draft_pk)
    
    # Create a new BlogPost instance
    job_post = models.JobPost(
        author=job_draft.author,
        title=job_draft.title,
        date= job_draft.date,
        location=job_draft.location,
        category=job_draft.category,
        content=job_draft.content
    )
    # save the draft to the job post model-- published
    job_post.save()
    
    # Delete the draft post
    job_draft.delete()
    
    return redirect('jobs:job_list')  # Redirect to the blog post list page




class EditJobDraftPostView(UpdateView):
    model = models.JobSaveAsDraft
    template_name = 'jobs/edit_job_draft_post.html'
    form_class = job_forms.JobDraftPostForm



    

class DeleteJobDraftPostView(DeleteView):
    model = models.JobSaveAsDraft
    success_url = reverse_lazy('jobs:job_drafts_list')
    template_name = 'jobs/delete_job_draft_post.html'
    

job/templates/jobs/delete_job_draft_post.html
{% extends 'home/base.html' %} 
{% block title %}  Delete {{object.title}} {% endblock %}

{% block body %} 
{% if user.is_authenticated %}
    <h1> DELETE JOB POST</h1><br> <br>
    <h3><em>Delete: </em>  {{object.title}} </h3>
    {% if object.author.id == user.id  %}
            <p>
                {{object.content | safe | truncatewords:"80"}}
            </p>

            <div class="form-group"> 
                <form method="POST">
                    {% csrf_token %}             
                    <button class="btn btn-danger">Delete</button>
                    <a href="{% url 'jobs:job_drafts_list' %}" class="btn btn-secondary">Cancel</a>
                </form> <br><br>
            </div>
    {% else %} 
            <h3>You don't have the access to delete this post</h3> <br> <br>
            <a class="btn btn-primary" href="{% url 'index:blog_list' %}">View Blog Posts</a> 
            <a class="btn btn-primary" href="{% url 'jobs:job_list' %}">View Job Posts</a> <br><br><br>
    {% endif %}

{% else %} 
<div class="alert alert-danger" role="alert">
    <p>You don't have the permission to access this page...</p>
    <p><a href="{% url 'login' %}">LOGIN</a> to delete post</p>    
</div> <br> <br>
    <a class="btn btn-primary" href="{% url 'index:home' %}">Go Home</a> <br><br><br>

{% endif %}
{% endblock %}

job/templates/jobs/drafts_job_details.html
{% extends 'home/base.html' %}
{% load static %}
{% load humanize %} <!---to display date in a natural time-->
{% load mptt_tags %}



{% block title %}{{ object.title }}{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="post-container">
                <div class="post-title">
                    <h1>{{ object.title | upper }}</h1>
                    {% if user.is_authenticated %}
                    <small>
                        <b>Last Updated:</b> {{ object.date }} | <b>Author:</b> {{ object.author.first_name }}
                        {{ object.author.last_name }} |
                        <b>Category:</b> <a href="{% url 'jobs:job_category_list' object.category %}">{{ object.category }}</a> |
                        {% if object.author.id == user.id %}
                        <a href="{% url 'jobs:edit_job_draft_post' object.pk %}">(Edit)</a>  
                        |    <a href="{% url 'jobs:delete_job_draft_post' object.pk %}">(Delete)</a>
                        |     <a href="{% url 'jobs:publish_job_draft' object.pk %}">(Publish Job)</a>
                        {% endif %}
                    </small> <hr>
                    <p>
                        {{ object.content | safe }}
                    </p>
                    <hr>
                    
                <a href="{% url 'jobs:publish_job_draft' object.pk %}"><button class="btn btn-success">Publish</button></a>
                  
                
                    {% else %}
                    <div class="alert alert-danger" role="alert">
                        <p>You don't have the permission to access this page...</p>
                        <p><a href="{% url 'login' %}">LOGIN</a> to viw draft post</p>    
                    </div>
                    {% endif %}
                </div>
<br><br>

  <!--- show the blogger info-->
  <div class="card mb-3" >                                                             
    <div class="card mb-3"  >
         <div class="row g-0">
            <div class="col-md-2">
                {% if object.author.profile.profile_pic %}
                    <img src="{{ object.author.profile.profile_pic.url }}" class="rounded-circle" alt="Author profile image" width="120" height="120">
                {% else %}
                    <img src="{% static 'images/profile_user_icon.png' %}" class="rounded-circle" alt="Default profile image" width="170" height="170">
                {% endif %}
            </div>
            
         <div class="col-md-10">
         <div class="card-body">
              <h5 class="card-title">{{object.author.first_name|safe}} {{object.author.last_name|safe}}</h5>

              <small  class="fw-lighter">
                   {% if object.author.profile.website_url %}
                   <a href="{{object.author.profile.website_url}}" target="_blank">Website </a>                                     
              {% endif %}


              {% if object.author.profile.facebook_url %}
                   |  <a href="{{object.author.profile.facebook_url}}" class="links" target="_blank">Facebook </a>                                  
              {% endif %}


              {% if object.author.profile.linkedln_url %}
                   |  <a href="{{object.author.profile.linkedln_url}}" class="links" target="_blank">Linkedln </a> 
              {% endif %}


              {% if object.author.profile.twitter_url %}
                   |  <a href="{{object.author.profile.twitter_url}}" class="links" target="_blank">Twitter </a> 
              {% endif %}

              {% if object.author.profile.instagram_url %}                                   
                   |  <a href="{{object.author.profile.instagram_url}}" class="links" target="_blank">Instagram </a>                                  
              {% endif %}                                   


              {% if object.author.profile.whatsapp_url %} 
                   |  <a href="{{object.author.profile.whatsapp_url}}" class="links" target="_blank"> WhatsApp </a>
              {% endif %}


              {% if object.author.profile.github_url %}

                   |  <a href="{{object.author.profile.github_url}}" class="links" target="_blank">GitHub </a> 
              {% endif %}

              </small>
              <p class="card-text">
                {% if object.author.profile and object.author.profile.id %}
                   {{object.author.profile.bio |truncatewords:"50" |safe}} 
                   ... <a href="{% url 'account:user_profile' object.author.profile.id %}" class="link-info link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                       Read More...
                   </a> 
                {% endif %}           
              </p>
              
             
          
          
         </div>
         </div>
         </div>
    </div>
  </div>

  <!---  End of show the blogger info-->
             

                                 
                      
                <br><br>
                <a href="{% url 'jobs:job_drafts_list' %}" class="btn btn-primary">Back To Draft List</a><br><br>
            </div>
        </div>
    </div>
</div>


             
<style>
    .post-title {
        margin: auto;
        text-align: justify;
        max-width: 55rem;
        width: 100%;
    }
</style>
{% endblock %}

job/templates/jobs/job_category_list.html
{% extends 'home/base.html' %} 
{% block title %} View Job Category {% endblock %}

{% block body %} 
<h1>Job Categories</h1>
    {% if category_list %}
        <ol>
            {% for item in category_list %} 
            <li>
                <h4><a href="{% url 'jobs:job_category_list' item %}">  {{item}} </a></h4> 
            </li>
        
   
{% endfor %} <br><br>
    </ol>
    {% endif %}
{% endblock %}

job/templates/jobs/job_details.html
{% extends 'home/base.html' %}
{% load static %}
{% load humanize %} <!---to display date in a natural time-->


{% block title %}{{ object.title }}{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="post-container">
                <div class="post-title">
                    <h1>{{ object.title | upper }}</h1>
                    {% if user.is_authenticated %}
                    <small>
                        <b>Last Updated:</b> {{ object.date }} ({{object.date | naturaltime}})  | <b>Posted By:</b> {{ object.author.last_name }}
                        {{ object.author.first_name }} |
                        <b>Category:</b> <a href="{% url 'jobs:job_category_list' object.category %}">{{ object.category }}</a> | <br>
                        <b> Job Location: </b> {{object.location}} |    <b>  Deadline:</b> {{object.deadline}} 
                        {% if object.author.id == user.id %}
                        <a href="{% url 'jobs:edit_job_post' object.pk %}">(Edit)</a> |
                        <a href="{% url 'jobs:delete_job_post' object.pk %}">(Delete)</a>
                        {% endif %}
                    </small> 
                    <p> <hr>
                        {{ object.content | safe }}                      
                    </p>
                    <hr>
                    {% if object.author.first_name == 'Yusuf' and object.author.last_name == 'Jamiu' %}                                                            
                     <a href="https://chat.whatsapp.com/J1Uyifhz2HWAhzkf24MqDv">  <button  class="btn btn-info">Join Our WhatsApp Group </button>  </a>                                                   
                    {% endif %}
                    
                    {% else %}
                    <div >
                        <small>
                            <b>Last Updated:</b> {{ object.date }} ({{object.date | naturaltime}})  | <b>Posted By:</b> {{ object.author.last_name }}
                            {{ object.author.first_name }} |
                            <b>Category:</b> <a href="{% url 'jobs:job_category_list' object.category %}">{{ object.category }}</a> | <br>
                            <b> Job Location: </b> {{object.location}} |    <b>  Deadline:</b> {{object.deadline}}                             
                        </small>  <br> <br>
                        <p>
                            {{ object.content | safe }}
                        </p>
                        <hr>
                    {% if object.author.first_name == 'Yusuf' and object.author.last_name == 'Jamiu' %}                                                            
                     <a href="https://chat.whatsapp.com/J1Uyifhz2HWAhzkf24MqDv">  <button  class="btn btn-info">Join Our WhatsApp Group </button>  </a>                                                   
                    {% endif %}
                    <br><br>
                        <small>
                            <a href="{% url 'login' %}">Login</a> to  Comment(s).                          
                        </small>
                    </div>
                    {% endif %}
                </div> <br>

                 <!--- show the blogger info-->
  <div class="card mb-3" >                                                             
    <div class="card mb-3"  >
         <div class="row g-0">
            <div class="col-md-2">
                {% if object.author.profile.profile_pic %}
                    <img src="{{ object.author.profile.profile_pic.url }}" class="rounded-circle" alt="Author profile image" width="120" height="120">
                {% else %}
                    <img src="{% static 'images/profile_user_icon.png' %}" class="rounded-circle" alt="Default profile image" width="170" height="170">
                {% endif %}
            </div>
            
         <div class="col-md-10">
         <div class="card-body">
              <h5 class="card-title">{{object.author.first_name|safe}} {{object.author.last_name|safe}}</h5>

              <small  class="fw-lighter">
                   {% if object.author.profile.website_url %}
                   <a href="{{object.author.profile.website_url}}" target="_blank">Website </a>                                     
              {% endif %}


              {% if object.author.profile.facebook_url %}
                   |  <a href="{{object.author.profile.facebook_url}}" class="links" target="_blank">Facebook </a>                                  
              {% endif %}


              {% if object.author.profile.linkedln_url %}
                   |  <a href="{{object.author.profile.linkedln_url}}" class="links" target="_blank">Linkedln </a> 
              {% endif %}


              {% if object.author.profile.twitter_url %}
                   |  <a href="{{object.author.profile.twitter_url}}" class="links" target="_blank">Twitter </a> 
              {% endif %}

              {% if object.author.profile.instagram_url %}                                   
                   |  <a href="{{object.author.profile.instagram_url}}" class="links" target="_blank">Instagram </a>                                  
              {% endif %}                                   


              {% if object.author.profile.whatsapp_url %} 
                   |  <a href="{{object.author.profile.whatsapp_url}}" class="links" target="_blank"> WhatsApp </a>
              {% endif %}


              {% if object.author.profile.github_url %}

                   |  <a href="{{object.author.profile.github_url}}" class="links" target="_blank">GitHub </a> 
              {% endif %}

              </small>
              <p class="card-text">
                {% if object.author.profile and object.author.profile.id %}
                   {{object.author.profile.bio |truncatewords:"50" |safe}} 
                   ... <a href="{% url 'account:user_profile' object.author.profile.id %}" class="link-info link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                       Read More...
                   </a> 
                {% endif %}           
              </p>
              
             
          
          
         </div>
         </div>
         </div>
    </div>
  </div>

  <!---  End of show the blogger info-->


                    <!-- Comment tags -->
                    <div>
                        {% with total_comments as comments_count %}
                        <h2>
                            {{ comments_count }} Comment{{ comments_count|pluralize }}
                        </h2>
                        <small> Job Title: {{object.title}} </small>
                        {% endwith %}    
                    </div>
                    <hr>
                    <div>
                    {% for comment in comments %}
                    <div style="border: 1px solid gray;">
                                <div class="d-flex" >
                                    <div class="p-2 flex-grow-1"><b>{{ comment.user }}</b></div>
                                    <div class="p-2"><small>{{ comment.date }} ({{ comment.date|naturaltime }})</small></div>                                                            
                                </div> 
                                <hr>                       
                                <div class="comments" >  {{ comment.content | safe |linebreaks }}</div>
                    </div>  <br>                  
                    {% empty %}
                        <p>There are no comments for this job post</p>
                    {% endfor %}
                    </div>

                    
                    <!-- Pagination -->
                    <div class="pagination">
                        {% if comments.has_previous %}
                            <a href="?page={{ comments.previous_page_number }}" class="pagination-link">Previous</a>
                        {% endif %}
                        {% for page_num in comments.paginator.page_range %}
                            {% if page_num == comments.number %}
                                <span class="pagination-number current-page">{{ page_num }}</span>
                            {% else %}
                                <a href="?page={{ page_num }}" class="pagination-link">{{ page_num }}</a>
                            {% endif %}
                        {% endfor %}
                        {% if comments.has_next %}
                            <a href="?page={{ comments.next_page_number }}" class="pagination-link">Next</a>
                        {% endif %}
                    </div>
                    <!---End of Pagination-->

                    <!-- Make a new comment -->
                    <br><br><br>
                    {% if user.is_authenticated %}
                    <h2 style="text-align: center;">Make A New Comment.</h2>
                    <form action="{% url 'jobs:add_job_comment' object.id %}" method="post">
                        {{ comment_form.as_p }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-secondary">Add Comment</button>
                    </form>
                    {% endif %}
                    <!-- End of Make a new comment -->

                    <!-- Comment tags -->


               
                
                   

                <br><br>
                <a href="{% url 'jobs:job_list' %}" class="btn btn-primary">Back To Job List</a><br><br>
            </div>
        </div>
    </div>
</div>


<style>
    .post-title {
        margin: auto;
        text-align: justify;
        max-width: 55rem;
        width: 100%;
    }

    .comments{
        padding: 1.2rem;    
    }    

    .pagination {
        margin-top: 20px;
        text-align: center;
    }

    .pagination-link {
        display: inline-block;
        margin-right: 5px;
        padding: 5px 10px;
        background-color: #f2f2f2;
        color: #333;
        text-decoration: none;
        border-radius: 5px;
    }

    .pagination-link:hover {
        background-color: #ccc;
    }

    .current-page {
        font-weight: bold;
    }
</style>
{% endblock %}