account/urls.py
from django.urls import path
from . views import UserRegisterView, UserEditProfileView, ChangePasswordView, ShowUserProfile, EditProfilePageView, CreateProfilePageVIew, ForgotPasswordView 
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),

    
   
    path('password/', ChangePasswordView.as_view(template_name='registration/change_password.html'), name='password'),
    path('changed_password_successfully/', views.changed_password_successfully, name='changed_password_successfully'),

    path('edit_profile/', UserEditProfileView.as_view(), name='edit_profile'),
    path('<int:pk>/profile', ShowUserProfile.as_view(), name='user_profile'),
    path('<int:pk>/edit_profile_page', EditProfilePageView.as_view(), name='edit_profile_page'),  
    path('create_profile_page/', CreateProfilePageVIew.as_view(), name='create_profile'),

    path('forgot_password/', ForgotPasswordView.as_view(), name='forgot_password'), 
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'), 
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

contact/urls.py
from . import views
from django.urls import path

app_name = 'contact'

urlpatterns = [
    path('contact/', views.Contact, name='contact'),
    #path('contact_success/', views.Contact_success, name='contact_success')    
]

index/urls.py
from . import views
from django.urls import path
from . views import  BlogHomeView, BlogDetailsView, AddPostView, EditPostView, DeletePostView, AddCategoryView, DraftsListView, AddDraftPostView, DraftPostDetailsView, EditDraftPostView, DeleteDraftPostView
from  django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage


app_name = 'index'

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),
    
    path('', views.home, name = 'home'),

    path('blog/', BlogHomeView.as_view(), name="blog_list"),
    path('blog/<int:pk>/', BlogDetailsView.as_view(), name='blog_details'),

    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('blog/edit/<int:pk>', EditPostView.as_view(), name='edit_post' ),
    path('blog/<int:pk>/delete', DeletePostView.as_view(), name='delete_post' ),
    path('like/<int:pk>', views.LikeView, name='like_post'),
    
    
    path('add_category/', AddCategoryView.as_view(), name='add_category'),       
    path('category/<str:category_name>/', views.CategoryView, name='category_list'), 
    path('view_category/', views.ListCategory, name='view_category'), 

    path('<int:pk>/add_comment/', views.add_comment, name='add_comment'),

    path('search/', views.search_results, name='search_results'),

    path('telecom/', views.telecom, name='telecom'),

    path('drafts/', DraftsListView.as_view(), name='drafts_list'),
    path('add_draft_post/', AddDraftPostView.as_view(), name='add_draft_post'),
    path('draft_details/<int:pk>/', DraftPostDetailsView.as_view(), name='draft_details'),
    path('draft/edit/<int:pk>', EditDraftPostView.as_view(), name='edit_draft_post' ),
    path('draft/<int:pk>/delete', DeleteDraftPostView.as_view(), name='delete_draft_post' ),
    path('publish/<int:draft_pk>/', views.publish_draft, name='publish_draft'),

]

job/urls.py
from django.shortcuts import render, redirect
from . import views
from django.urls import path
from . views import JobHomeView, JobDetailsView, AddJobPostView, EditJobPostView, DeleteJobPostView, AddJobCategoryView, JobDraftPostDetailsView, JobDraftsListView, AddJobDraftPostView, EditJobDraftPostView, DeleteJobDraftPostView
from  django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage



app_name = 'jobs'

urlpatterns = [
    path('job/', JobHomeView.as_view(), name="job_list"),
    path('job/<int:pk>/', JobDetailsView.as_view(), name='job_details'),


    path('add_job_post/', AddJobPostView.as_view(), name='add_job_post'),
    path('job/edit/<int:pk>', EditJobPostView.as_view(), name='edit_job_post' ),
    path('job/<int:pk>/delete', DeleteJobPostView.as_view(), name='delete_job_post' ),
    
    path('add_job_category/', AddJobCategoryView.as_view(), name='add_job_category'),       
    path('job_category/<str:category_name>/', views.JobCategoryView, name='job_category_list'), 
    path('view_job_category/', views.ListJobCategory, name='view_job_category'), 

    path('<int:pk>/add_job_comment/', views.add_job_comment, name='add_job_comment'),


    path('job_drafts/', JobDraftsListView.as_view(), name='job_drafts_list'),
    path('add_job_draft_post/', AddJobDraftPostView.as_view(), name='add_job_draft_post'),
    path('job_draft_details/<int:pk>/', JobDraftPostDetailsView.as_view(), name='job_draft_details'),
    path('job_draft/edit/<int:pk>', EditJobDraftPostView.as_view(), name='edit_job_draft_post' ),
    path('job_draft/<int:pk>/delete', DeleteJobDraftPostView.as_view(), name='delete_job_draft_post' ),
    path('publish/<int:job_draft_pk>/', views.publish_job_draft, name='publish_job_draft'),
]

learwithjdd/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls")),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')), 
    path('contact/', include('contact.urls')),
    path('job/', include('job.urls')),
    path('discussion/', include('discussion.urls')),
    path('tasks/', include('tasks.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from . import views 
from . views import AddTaskView, TaskListView


app_name = 'tasks'
urlpatterns = [
    path('task_lists', TaskListView.as_view(), name='tasks_list'),
    path('add_tasks', AddTaskView.as_view() , name='add_tasks'),

    path("complete-task/", views.TaskCompleteView.as_view(), name="complete_task"),

    path("delete-completed-tasks/", views.DeleteCompletedTasksView.as_view(), name="delete_completed_tasks"),
    path("edit-task/<int:pk>/", views.EditTaskView.as_view(), name="edit_task"),
    path("delete-task/<int:pk>/", views.DeleteTaskView.as_view(), name="delete_task"),

    path('update_status/', views.UpdateStatusView.as_view(), name='update_status'),
]

index/templates/home/base.html
{% load static %}
{% load humanize %}

<!doctype html>
<html lang="en" >
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.rtl.min.css" integrity="sha384-T5m5WERuXcjgzF8DAb7tRkByEZQGcpraRTinjpywg37AO96WoYN9+hrhDVoM6CaT" crossorigin="anonymous">
    
    <link rel="shortcut icon" type="image/png" href="{% static '/images/favicon_io/favicon.ico' %}">

    <!---- JQuery for the comment section-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!---ckeditor-->
    <script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

    <!--- Inventory management imports-->
     
       <!--Chartjs CDN-->
     <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    
     <!---  End of Inventory management imports-->

    
    <title>{% block title %} {% endblock %}</title>
  </head>

  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index:home' %}">JDD</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index:home' %}">Home</a>
            </li>   

            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              Tools
              </a>
              <ul class="dropdown-menu">   
                <li><a class="dropdown-item" href="{% url 'discussion:discuss_list' %}">Chat & Discussion</a></li>                                                                               
                <li><a class="dropdown-item" href="{% url 'tasks:tasks_list' %}">Task Management</a></li>  
                <li class="nav-item"><a class="nav-link" href="{% url 'index:telecom' %}" target="_blank" >Telecom</a></li> 
                <li><a class="dropdown-item" href="https://afr.808scoretv.com/" target="_blank">Watch Live Matches</a></li>                                                                             
              </ul>
            </li>
          
            {% if user.is_authenticated %}
                 
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url 'index:blog_list' %}" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              Blog
              </a>
              <ul class="dropdown-menu">   
                <li><a class="dropdown-item" href="{% url 'index:blog_list' %}">Post </a></li>
                <li><a class="dropdown-item" href="{% url 'index:drafts_list' %}"> Create/View Draft Post </a></li>                              
                <li><a class="dropdown-item" href="{% url 'index:add_post' %}">Publish A New Post</a></li>                  
                <li><hr class="dropdown-divider"></li>  
                <li><a class="dropdown-item" href="{% url 'index:add_category' %}">Add A New Blog Category</a></li>   
                <li><a class="dropdown-item" href="{% url 'index:view_category' %}">View Post Categories</a></li>                                                                             
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url 'index:blog_list' %}" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
               Jobs
              </a>
              <ul class="dropdown-menu">   
                <li><a class="dropdown-item" href="{% url 'jobs:job_list' %}">Job Listing</a></li>
                <li><a class="dropdown-item" href="{% url 'jobs:job_drafts_list' %}"> Create/View Draft Job Post </a></li>                               
                <li><a class="dropdown-item" href="{% url 'jobs:add_job_post' %}">Add A New Job Post</a></li>  
                <li><hr class="dropdown-divider"></li>  
                <li><a class="dropdown-item" href="{% url 'jobs:add_job_category' %}">Add A New Job Category</a></li>   
                <li><a class="dropdown-item" href="{% url 'jobs:view_job_category' %}">View Job Categories</a></li>                                                                             
              </ul>
            </li>


                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    {% if user.profile.profile_pic %}
                    <img src="{{ user.profile.profile_pic.url }}" class="rounded-circle" alt="Author profile image" width="30" height="30"> {{ user }}
                    {% else %}
                        <img src="{% static 'images/profile_user_icon.png' %}" class="rounded-circle" alt="Default profile image" width="20" height="20"> {{user}}
                    {% endif %}
                    </a>
                    <ul class="dropdown-menu">    
                    {% if user.profile.id %}
                          <li><a class="dropdown-item" href="{% url 'account:edit_profile_page' user.profile.id %}"> Edit Profile </a></li>
                          <li><a class="dropdown-item" href="{% url 'account:user_profile' user.profile.pk %}">View Profile</a></li> 
                    {% else %} 
                          <li><a class="dropdown-item" href="{% url 'account:create_profile' %}">Create Profile </a></li>  
                    {% endif %}                       
                      <li><a class="dropdown-item" href="{% url 'account:edit_profile' %}"> Settings </a></li> 
                      <li><hr class="dropdown-divider"></li>                                                 
                      <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>                                                                                                                        
                    </ul>
                  </li>   
                  
            {% else %}                                               
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                     data-bs-toggle="dropdown" aria-expanded="false">
                     Account
                    </a>
                    <ul class="dropdown-menu">   
                      <li><a class="dropdown-item" href="{% url 'account:register' %}">Register</a></li>   
                      <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>                                         
                      <li><hr class="dropdown-divider"></li>                
                    </ul>
                  </li>

                   <li class="nav-item">
                  <a class="nav-link" href="{% url 'index:blog_list' %}">Posts</a>
                </li>

              <li class="nav-item">
              <a class="nav-link" href="{% url 'jobs:job_list' %}">Jobs Listing</a>
              </li>


            {% endif %}
                                   
          </ul>

          {% include 'home/search.html' %}

        </div>
      </div>
    </nav>

    {% block slides %} {% endblock %}
  </header>



  <body>
    <div class="container"> <br>
        {% block body %} {% endblock %}
      </div>
    
  </body>

  <footer>
<br><br><br><br>
    <div class="row">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">What We Do?</h5>
            <p class="card-text" style="text-align: justify;">
              We are a team of people who appreciate taking on challenging and unattainable tasks and have a variety of skill sets.
              Let us assist you with designing, security, and managing your personal, portfolio, and company websites, 
              mobile applications, and web applications.
              
            </p>
            <p style="text-align: justify;">
               Additionally, We offer an extensive range of services, including the sale of digital products, architectural designs, telecommunications solutions 
              like the sale of internet access for all Nigerian networks, job posting services like writing Cvs or Resumes, 
              cover letters, reference letters, recruitment advice, business management, and much more. 
              Also, we relieve you of the burden associated with your academic and business research projects, such 
              as your final year project, school assignments (for all courses, departments, and levels), business plans, 
              feasibility analyses, business proposals, etc.           
            </p>            
            <a href="{% url 'contact:contact' %}" class="btn btn-primary">Send Us Message</a>
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Other Links</h5>
            <ul>                                     
              <li><a href="{% url 'index:blog_list' %}" class="footer-link">Blog</a></li>
              <li><a href="{% url 'discussion:discuss_list' %}" class="footer-link">Chat & Discussion</a></li>
              <li><a href="{% url 'jobs:job_list' %}" class="footer-link">Jobs</a></li> 
              <li><a href="{% url 'index:home' %}" class="footer-link">Home</a></li>                                                     
              <li><a href="{% url 'tasks:tasks_list' %}" class="footer-link">Task Management Help</a></li>
              <li ><a  href="{% url 'index:telecom' %}" target='_blank' class="footer-link">Telecom</a></li>  
              <li><a href="https://afr.808scoretv.com/" class="footer-link" target="_blank">Watch Live Football Matches</a></li>                                        
            </ul>           
          </div>
        </div>
      </div>
    </div>

    <style>
      .footer-link{
        text-decoration: none;
        color: black;
      }

      .footer-link:hover{
        color: rgb(70, 70, 226);
        font-size: 1.5rem;
      }

      .footer-link li {
        list-style-type: none;
        text-align: justify;
      }
    </style>

  </footer>

   <!-- Option 1: Bootstrap Bundle with Popper -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>


</html>

index/templates/home/blog_list.html
{% extends 'home/base.html' %}
{% block title %} Blog Posts {% endblock %} 


{% block body %} 

    <h1>BLOG POSTS</h1> <br>
    
        <ol>
        {% for blog in object_list %} 
        <li>
           <h4><a href="{% url 'index:blog_details' blog.pk %}"> {{blog.title | upper}}</a></h4> 
           {% if user.is_authenticated %}
                <small>
                   <b>Last Updated:</b>  {{blog.date}} | <b>Author: </b>                    
                        {{blog.author.first_name}} {{blog.author.last_name}} | 
                   <b>Category:</b>  <a href="{% url 'index:category_list' blog.category %}">{{blog.category}}</a> 
                {% if blog.author.id == user.id  %}
                    | <a href="{% url 'index:edit_post' blog.pk %}">(Edit)</a> 
                    | <a href="{% url 'index:delete_post' blog.pk %}">(Delete)</a>
                {% endif %}    
                </small>    
                <p> 
                       <!---{{blog.content | truncatewords:"80" | safe}}--> 
                       {{blog.headline | safe}}
                </p>
        {% else %} 
                <small>
                   <b> Category:</b>  <a href="{% url 'index:category_list' blog.category %}">{{blog.category}}</a> |
                   <b>  Last Updated:</b> {{blog.date}} | <b>Author: </b>  {{blog.author.first_name}} {{blog.author.last_name}} |                    
                </small>    
                <p>
                        <!-----{{blog.content | truncatewords:"80" | safe}}--->
                        {{blog.headline | safe}}
                </p>                
        {% endif %}
            
        </li> <br>
            
        
        {% empty %} 
            <h2>No recent posts availabe at the moment....</h2>
        {% endfor %}
    </ol>


{% endblock %}

index/templates/home/category_not_found.html
{% extends 'home/base.html' %} 
{% block title %} Page Not Found {% endblock %}

{% block body %}

<h1>Category not found</h1>
<p>The requested category does not exist.</p>

<a class="btn btn-primary" href="{% url 'index:blog_list' %}">View Blog Posts</a> 
<a class="btn btn-primary" href="{% url 'jobs:job_list' %}">View Job Posts</a> <br><br><br>

{% endblock %}

index/templates/home/category_view.html
{% extends 'home/base.html' %} 
{% block title %} {{category.name | upper}} POSTS {% endblock %}

{% block body %} 
{% if posts %}
        <h1>{{category.name | upper}} POSTS  </h1><br> <br>

        <ol>
            {% for blog in posts %} 
            <li>
               <h4><a href="{% url 'index:blog_details' blog.pk %}"> {{blog.title | upper}}</a></h4> 
               {% if user.is_authenticated %}
                    <small>
                        Last Updated: {{blog.date}} | Author: {{blog.author}} | 
                        Category: <a href="{% url 'index:category_list' blog.category %}">{{blog.category}}</a> |
                    {% if blog.author.id == user.id  %}
                        <a href="{% url 'index:edit_post' blog.pk %}">(Edit)</a> |
                        <a href="{% url 'index:delete_post' blog.pk %}">(Delete)</a>
                    
                    {% endif %}
                    </small>    
                    <p>
                            {{blog.content | truncatewords:"80" | safe}}
                    </p>
            {% else %} 
                    <small>
                        Last Updated: {{blog.date}} | Author: {{blog.author}} |                    
                    </small>    
                    <p>
                            {{blog.content | truncatewords:"80" | safe}}
                    </p>
            {% endif %}
                
            </li>
                
            
            {% empty %} 
                <h2>No recent posts availabe for this category....</h2>
            {% endfor %}
        </ol>
    {% else %} 
            <h4>This page do not exists</h4>
    {% endif %}

    <br><br> <a class="btn btn-primary" href="{% url 'index:blog_list' %}">View Blog Posts</a>  <br><br><br>
    
{% endblock %}

index/templates/home/delete_post.html
{% extends 'home/base.html' %} 
{% block title %}  Delete Post {% endblock %}

{% block body %} 
{% if user.is_authenticated %}
    <h1> DELETE BLOG POST</h1><br> <br>
    <h3><em>Delete: </em>  {{object.title}} </h3>
    {% if object.author.id == user.id  %}
            <p>
                {{object.content | safe | truncatewords:"80"}}
            </p>

            <div class="form-group"> 
                <form method="POST">
                    {% csrf_token %}             
                    <button class="btn btn-danger">Delete</button>
                    <a href="{% url 'index:blog_list' %}" class="btn btn-secondary">Cancel</a>
                </form> <br><br>
            </div>
    {% else %} 
            <h3>You don't have the access to delete this post</h3> <br> <br>
            <a class="btn btn-primary" href="{% url 'index:blog_list' %}">View Blog Posts</a> 
            <a class="btn btn-primary" href="{% url 'index:job_list' %}">View Job Posts</a> <br><br><br>
    {% endif %}

{% else %} 
<div class="alert alert-danger" role="alert">
    <p>You don't have the permission to access this page...</p>
    <p><a href="{% url 'login' %}">LOGIN</a> to delete post</p>    
</div> <br> <br>
    <a class="btn btn-primary" href="{% url 'index:home' %}">Go Home</a> <br><br><br>

{% endif %}
{% endblock %}

index/templates/home/draft_list.html
{% extends 'home/base.html' %}
{% load humanize %}

{% block title %} Draft Posts {% endblock %} 


{% block body %} 

<div class="d-flex">
    <div class="p-2 w-100">
      <h1>DRAFT POSTS</h1>
    </div>
    <div class="p-2 flex-shrink-1">
      <a href="{% url 'index:add_draft_post' %}">
        <button>Create A New Draft Post</button>
      </a>
    </div>
  </div>

<br><br>
    
        <ol>
        {% for draft in object_list %} 
        <li>
           <h4><a href="{% url 'index:draft_details' draft.pk %}"> {{draft.title | upper}}</a></h4> 
           {% if user.is_authenticated %}
                <small>
                   <b>Last Updated:</b>  {{draft.date}}({{draft.date | naturaltime}}) |
                    <b>Author: </b>                    
                        {{draft.author.first_name}} {{draft.author.last_name}} | 
                   <b>Category:</b>  <a href="{% url 'index:category_list' draft.category %}">{{draft.category}}</a> |
                   <br>
                {% if draft.author.id == user.id  %}
                     <a href="{% url 'index:edit_draft_post' draft.pk %}">(Edit)</a>  
                    |    <a href="{% url 'index:delete_draft_post' draft.pk %}">(Delete)</a>
                    |     <a href="{% url 'index:publish_draft' draft.pk %}">(Publish)</a>
                {% endif %}    
                </small>    
                <hr>
                <p> 
                       <!---{{blog.content | truncatewords:"80" | safe}}--> 
                       {{draft.headline | safe}}
                </p>
        {% else %} 
                <small>
                   <b> Category:</b>  <a href="{% url 'index:category_list' draft.category %}">{{draft.category}}</a> |
                   <b>  Last Updated:</b> {{draft.date}} | <b>Author: </b>  {{draft.author.first_name}} {{draft.author.last_name}} |                    
                </small>    
                <p>
                        <!-----{{blog.content | truncatewords:"80" | safe}}--->
                        {{draft.headline | safe}}
                </p>                
        {% endif %}
            
        </li> <br>
            
        
        {% empty %} 
            <h2>No draft posts created yet....</h2>
        {% endfor %}
    </ol>


{% endblock %}

index/templates/home/drafts_details.html
{% extends 'home/base.html' %}
{% load static %}
{% load humanize %} <!---to display date in a natural time-->
{% load mptt_tags %}



{% block title %}{{ object.title }}{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="post-container">
                <div class="post-title">
                    <h1>{{ object.title | upper }}</h1>
                    {% if user.is_authenticated %}
                    <small>
                        <b>Last Updated:</b> {{ object.date }} | <b>Author:</b> {{ object.author.first_name }}
                        {{ object.author.last_name }} |
                        <b>Category:</b> <a href="{% url 'index:category_list' object.category %}">{{ object.category }}</a> |
                        {% if object.author.id == user.id %}
                        <a href="{% url 'index:edit_draft_post' object.pk %}">(Edit)</a>  
                        |    <a href="{% url 'index:delete_draft_post' object.pk %}">(Delete)</a>
                        |     <a href="{% url 'index:publish_draft' object.pk %}">(Publish)</a>
                        {% endif %}
                    </small> <hr>
                    <p>
                        {{ object.content | safe }}
                    </p>
                    <hr>
                    
                <a href="{% url 'index:publish_draft' object.pk %}"><button class="btn btn-success">Publish</button></a>
                  
                
                    {% else %}
                    <div class="alert alert-danger" role="alert">
                        <p>You don't have the permission to access this page...</p>
                        <p><a href="{% url 'login' %}">LOGIN</a> to viw draft post</p>    
                    </div>
                    {% endif %}
                </div>
<br><br>

  <!--- show the blogger info-->
  <div class="card mb-3" >                                                             
    <div class="card mb-3"  >
         <div class="row g-0">
            <div class="col-md-2">
                {% if object.author.profile.profile_pic %}
                    <img src="{{ object.author.profile.profile_pic.url }}" class="rounded-circle" alt="Author profile image" width="120" height="120">
                {% else %}
                    <img src="{% static 'images/profile_user_icon.png' %}" class="rounded-circle" alt="Default profile image" width="170" height="170">
                {% endif %}
            </div>
            
         <div class="col-md-10">
         <div class="card-body">
              <h5 class="card-title">{{object.author.first_name|safe}} {{object.author.last_name|safe}}</h5>

              <small  class="fw-lighter">
                   {% if object.author.profile.website_url %}
                   <a href="{{object.author.profile.website_url}}" target="_blank">Website </a>                                     
              {% endif %}


              {% if object.author.profile.facebook_url %}
                   |  <a href="{{object.author.profile.facebook_url}}" class="links" target="_blank">Facebook </a>                                  
              {% endif %}


              {% if object.author.profile.linkedln_url %}
                   |  <a href="{{object.author.profile.linkedln_url}}" class="links" target="_blank">Linkedln </a> 
              {% endif %}


              {% if object.author.profile.twitter_url %}
                   |  <a href="{{object.author.profile.twitter_url}}" class="links" target="_blank">Twitter </a> 
              {% endif %}

              {% if object.author.profile.instagram_url %}                                   
                   |  <a href="{{object.author.profile.instagram_url}}" class="links" target="_blank">Instagram </a>                                  
              {% endif %}                                   


              {% if object.author.profile.whatsapp_url %} 
                   |  <a href="{{object.author.profile.whatsapp_url}}" class="links" target="_blank"> WhatsApp </a>
              {% endif %}


              {% if object.author.profile.github_url %}

                   |  <a href="{{object.author.profile.github_url}}" class="links" target="_blank">GitHub </a> 
              {% endif %}

              </small>
              <p class="card-text">
                {% if object.author.profile and object.author.profile.id %}
                   {{object.author.profile.bio |truncatewords:"50" |safe}} 
                   ... <a href="{% url 'account:user_profile' object.author.profile.id %}" class="link-info link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                       Read More...
                   </a> 
                {% endif %}           
              </p>
              
             
          
          
         </div>
         </div>
         </div>
    </div>
  </div>

  <!---  End of show the blogger info-->
             

                                 
                      
                <br><br>
                <a href="{% url 'index:drafts_list' %}" class="btn btn-primary">Back To Draft List</a><br><br>
            </div>
        </div>
    </div>
</div>


             
<style>
    .post-title {
        margin: auto;
        text-align: justify;
        max-width: 55rem;
        width: 100%;
    }
</style>
{% endblock %}